### ISSUE TITLE
Test airspeed režimu (https://github.com/PX4/PX4-Autopilot/pull/18419).

### ISSUE THREAD

**Issue by roman-dvorak** [ODZ-UJF-AV-CR/FIK-X#16]
### Airspeed mode https://github.com/PX4/PX4-Autopilot/pull/18419

Ovládání bylo velmi zajímavé a netradiční. Po chvilce letu se stalo dosti intuitivní a reakce řízení byla velmi dobrá. Test probíhal způsobem, že jsem vždy nastoupal přes 100 m a snažil jsem se klouzat s různým nastavením motoru. Při nízkém tahu motoru musela být nastavena docela vysoká dopředná rychlost (minimálně nad 75% výchylky) při bezmotorovém letu, docházelo ke klesání skoro na místě a následně došlo k protočení trupu (což je problematická vlastnost aktuální konstrukce vírníku) ale pokud jsem nastavil větší setpoint airspeed, tak se vírník choval velmi slušně. I při takovém klesání byl docela dobře ovladatelný (v roll). 

Bylo trošku složité v airspeed režimu získat nějakou výšku. Ale to je, myslím, způsobeno konstrukcí vírníku, která nestoupá stejným způsobem jako letadlo. 

Z letového pokusu, při kterém bylo provedeno několik bezmotorových klesání bych řekl, že tento režim je vhodný pro sestup z balónu. Je velmi důležité stanovit, jakou airspeed (popř. rozsah airspeed) se má snažit autopilot udržovat.

**Comment by kaklik** [comment]
Po posledních pokusech bych řekl, že tento test můžeme považovat za hotový.  Během dalších kroků půjde hlavně o zlepšení parametrů.
